[package]
name = "aws-project"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-ec2 = "1.88.0"
tokio = { version = "1", features = ["full"] }